# permissions for end users to view taskcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: taskcrd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: task-crd
    app.kubernetes.io/part-of: task-crd
    app.kubernetes.io/managed-by: kustomize
  name: taskcrd-viewer-role
rules:
- apiGroups:
  - webapp.xiaoyeshiyu.domain
  resources:
  - taskcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.xiaoyeshiyu.domain
  resources:
  - taskcrds/status
  verbs:
  - get
