apiVersion: webapp.xiaoyeshiyu.domain/v1
kind: TaskCrd
metadata:
  labels:
    app.kubernetes.io/name: task-crd
    app.kubernetes.io/managed-by: kustomize
  name: taskcrd-sample
  namespace: m1
spec:
  deployment: nginx
  hpa: php-apache
  average_utilization: 10
  start: "* * * * * *"
  max_replicas: 10
  end: "10 * * * * *"
  end_replicas: 1
